### ISSUE TITLE
Developement Roadmap

### ISSUE THREAD

**Issue by rockleona** [sciwork/banner_generator#1]
Hi there, feel free to comment or give suggestions!

**GUI Development**
+ [ ] tkinter? PyQt?

**Stack Optimize**
+ [ ] Better Way to Search Background Image
+ [ ] Configurable Folder, Files, Assets

**File Related**
+ [ ] Save File as Layer-editable
    + [ ] EPS? PDF?
+ [ ] Save Backround Image by Option

**Graphic Design**
+ [ ] Develop Different Layout
    + [ ] Logo and Title Align Left
    + [ ] Logo and Title Align Right
+ [ ] Add Subtitle or Content Area
+ [ ] AI-Generated Background?

**Comment by wdbps93206** [comment]
Hi! I think this is a helpful tool. I use this tool to create some suitable pictures from Unsplash. It saves many time and this is my comment.
> **GUI Development**
> 
> * [x]  PyQt
> 
> **Stack Optimize**
> 
> * [x]  Better Way to Search Background Image
> * [ ]  Configurable Folder, Files, Assets
> 
> **File Related**
> 
> * [x]  Save File as Layer-editable
>   
>   * [x]  PDF?
> * [x]  Save Backround Image by Option
> 
> **Graphic Design**
> 
> * [x]  Develop Different Layout
>   * [ ]  Logo and Title Align Left
>   * [x]  Logo and Title Align Right
> * [x]  Add Subtitle or Content Area
> * [x] AI-Generated 

> **Other:** Hopefully, one day can add some post-production features.
